apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: n8f2v52o1-java-springboot-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/n8f2v52o1-java-springboot-gitops